POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name":"test",
  "email":  "test2@email.com",
  "referrer":"9b06c6e0-8baa-4aa7-ac03-5345e4ab5b3c"
}

###

GET http://localhost:3333/invites/9b06c6e0-8baa-4aa7-ac03-5345e4ab5b3c


###


GET http://localhost:3333/subscribers/9b06c6e0-8baa-4aa7-ac03-5345e4ab5b3c/ranking/clicks



###

GET http://localhost:3333/subscribers/9b06c6e0-8baa-4aa7-ac03-5345e4ab5b3c/ranking/count


###

GET http://localhost:3333/subscribers/9b06c6e0-8baa-4aa7-ac03-5345e4ab5b3c/ranking/position


###

GET http://localhost:3333/ranking